// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilitaryVehicles.infrastructure;

#nullable disable

namespace MilitaryVehicles.infrastructure.Migrations
{
    [DbContext(typeof(MilitaryVehiclesContext))]
    [Migration("20251030003948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.ArmyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Armies");
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.CrewMemberModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArmyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.ToTable("MilitaryVehicles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VehicleCrewMember", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("VehicleCrewMembers", (string)null);
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.AirVehicleModel", b =>
                {
                    b.HasBaseType("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel");

                    b.ToTable("AirVehicles", (string)null);
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.GroundVehicleModel", b =>
                {
                    b.HasBaseType("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel");

                    b.ToTable("GroundVehicles", (string)null);
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.SeaVehicleModel", b =>
                {
                    b.HasBaseType("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel");

                    b.ToTable("SeaVehicles", (string)null);
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.HelicopterModel", b =>
                {
                    b.HasBaseType("MilitaryVehicles.infrastructure.Models.AirVehicleModel");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.ToTable("Helicopters", (string)null);
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.TankModel", b =>
                {
                    b.HasBaseType("MilitaryVehicles.infrastructure.Models.GroundVehicleModel");

                    b.Property<int>("Firepower")
                        .HasColumnType("INTEGER");

                    b.ToTable("Tanks", (string)null);
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.DestroyerModel", b =>
                {
                    b.HasBaseType("MilitaryVehicles.infrastructure.Models.SeaVehicleModel");

                    b.Property<int>("Torpedoes")
                        .HasColumnType("INTEGER");

                    b.ToTable("Destroyers", (string)null);
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.ArmyModel", "Army")
                        .WithMany("Vehicles")
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");
                });

            modelBuilder.Entity("VehicleCrewMember", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.CrewMemberModel", null)
                        .WithMany()
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.AirVehicleModel", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel", null)
                        .WithOne()
                        .HasForeignKey("MilitaryVehicles.infrastructure.Models.AirVehicleModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.GroundVehicleModel", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel", null)
                        .WithOne()
                        .HasForeignKey("MilitaryVehicles.infrastructure.Models.GroundVehicleModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.SeaVehicleModel", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.MilitaryVehicleModel", null)
                        .WithOne()
                        .HasForeignKey("MilitaryVehicles.infrastructure.Models.SeaVehicleModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.HelicopterModel", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.AirVehicleModel", null)
                        .WithOne()
                        .HasForeignKey("MilitaryVehicles.infrastructure.Models.HelicopterModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.TankModel", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.GroundVehicleModel", null)
                        .WithOne()
                        .HasForeignKey("MilitaryVehicles.infrastructure.Models.TankModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.DestroyerModel", b =>
                {
                    b.HasOne("MilitaryVehicles.infrastructure.Models.SeaVehicleModel", null)
                        .WithOne()
                        .HasForeignKey("MilitaryVehicles.infrastructure.Models.DestroyerModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryVehicles.infrastructure.Models.ArmyModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
